#!/usr/bin/env bash
# Automatically configure a Ubuntu machine

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
my_redirect="\\trewrite ^/redirect_me https://www.youtube.com/watch?v=dQw4w9WgXcQ permanent;"
sudo sed -i $"/server_name _;/a\\\n$my_redirect" /etc/nginx/sites-available/default
sudo service nginx restart