#!/usr/bin/env bash
# Configure web-02 to be identical to web-01

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
my_redirect="\\trewrite ^/redirect_me https://www.youtube.com/watch?v=dQw4w9WgXcQ permanent;"
sudo sed -i $"/server_name _;/a\\\n$my_redirect" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404_page.html
my_404="\\terror_page 404 /404_page.html;"
sudo sed -i $"/server_name _;/a\\\n$my_404" /etc/nginx/sites-available/default
sudo curl -H "X-Served-By: $HOSTNAME"
sudo service nginx restart