#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server.

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install haproxy
echo -e "frontend front_web_servers\n\
\tbind *:80\n\
\tmode http\n\
\tdefault_backend web-servers\n\n\
backend web-servers\n\
\tbalance roundrobin\n\
\tserver 55698-web-01 34.202.164.194:80 check\n\
\tserver 55698-web-02 52.3.252.70:80 check\n" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart