#!/usr/bin/env bash
# Configures server to run and listen on port 80 
# of all the server’s active IPv4 IPs

sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo service nginx restart 
