#!/usr/bin/env bash
# debugging nginx (service (init) must say that nginx is not running)
sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default #replace 8080 with 80
service nginx restart
pkill -o nginx
